from core.faqs import register_faqs

register_faqs("fourier-square-wave", [
    {"q": "Why does a square wave only contain odd harmonics?", "a": "A square wave has a special symmetry (it looks the same flipped and shifted by half a period), and that symmetry mathematically cancels every even harmonic. What is left is the 1st, 3rd, 5th... sine waves, each weaker than the last. Turn up N here and watch only the odd bars appear in the spectrum."},
    {"q": "What are those little overshoots near the edges?", "a": "That is the famous Gibbs phenomenon. Near a sudden jump, the partial Fourier sum always overshoots by about 9% of the jump height — and it never goes away no matter how many harmonics you add; it just gets narrower. It is why perfectly sharp edges are impossible to reproduce with a finite number of frequencies."},
    {"q": "Where do square waves show up in the real world?", "a": "Every digital clock signal inside your computer or phone is essentially a square wave — billions per second. So are PWM signals that dim LEDs and control motor speed. Understanding their harmonic content is how engineers stop those sharp edges from radiating interference into nearby radios and circuits."},
    {"q": "Why do square waves sound 'buzzy' or 'hollow'?", "a": "Because they contain only odd harmonics, a square wave has a distinctive reedy timbre — close to a clarinet, which also favours odd harmonics. Classic video-game and synth sounds are built from square waves for exactly this reason. Compare it with the sawtooth tab to hear why 'all harmonics' sounds brighter."},
    {"q": "How many harmonics do I need for a 'good' square wave?", "a": "There is no finite answer — a true square wave needs infinitely many. But the energy drops as 1/n, so the first 10–20 harmonics already look square to the eye. Drag N upward here and decide for yourself when it is 'square enough' — that engineering judgement is exactly what filter designers make every day."},
])
